# Generated by Django 3.1 on 2020-09-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saber2012',
            name='mod_lectura_critica',
            field=models.IntegerField(),
        ),
    ]
