# Generated by Django 3.1 on 2020-09-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20200925_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saber2012',
            name='mod_lectura_critica',
            field=models.FloatField(),
        ),
    ]
