# Generated by Django 3.1 on 2020-09-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20200925_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='saber2012',
            name='estu_colegiotermino_dept',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
