# Generated by Django 3.1 on 2020-09-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_auto_20200925_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimEstudiantes',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('eco_condicion_electrodomesticos', models.TextField(blank=True, null=True)),
                ('eco_condicion_tic', models.TextField(blank=True, null=True)),
                ('eco_condicion_vive', models.TextField(blank=True, null=True)),
                ('eco_condicion_vivienda', models.TextField(blank=True, null=True)),
                ('estu_consecutivo', models.TextField(blank=True, null=True)),
                ('estu_discapacidad', models.TextField(blank=True, null=True)),
                ('estu_genero', models.TextField(blank=True, null=True)),
                ('estu_numero_libros', models.TextField(blank=True, null=True)),
                ('estu_rango_edad', models.TextField(blank=True, null=True)),
                ('estu_trabaja', models.TextField(blank=True, null=True)),
                ('fami_estrato_vivienda', models.TextField(blank=True, null=True)),
                ('fami_ingreso_fmiliar_mensual', models.TextField(blank=True, null=True)),
                ('fami_max_nivel_educa_padres', models.TextField(blank=True, null=True)),
                ('fami_nivel_sisben', models.TextField(blank=True, null=True)),
                ('fami_ocup_madre', models.TextField(blank=True, null=True)),
                ('fami_ocup_padre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_estudiantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimInstituciones',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('cole_bilingue', models.TextField(blank=True, null=True)),
                ('cole_caracter', models.TextField(blank=True, null=True)),
                ('cole_genero', models.TextField(blank=True, null=True)),
                ('cole_jornada', models.TextField(blank=True, null=True)),
                ('cole_naturaleza', models.TextField(blank=True, null=True)),
                ('cole_nombre_sede', models.TextField(blank=True, null=True)),
                ('cole_calendario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_instituciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimLugares',
            fields=[
                ('id_lugar', models.AutoField(primary_key=True, serialize=False)),
                ('cole_area_ubicacion', models.TextField(blank=True, null=True)),
                ('cole_mcpio_ubicacion', models.TextField(blank=True, null=True)),
                ('estu_area_reside', models.TextField(blank=True, null=True)),
                ('estu_mcpio_presentacion', models.TextField(blank=True, null=True)),
                ('estu_reside_mcpio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_lugares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimPruCNat',
            fields=[
                ('id_pru_c_nat', models.AutoField(primary_key=True, serialize=False)),
                ('desemp_c_naturales', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_pru_c_nat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimPruIngles',
            fields=[
                ('id_pru_ingles', models.AutoField(primary_key=True, serialize=False)),
                ('desemp_ingles', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_pru_ingles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimPruLecCrit',
            fields=[
                ('id_pru_lec_crit', models.AutoField(primary_key=True, serialize=False)),
                ('desemp_lec_crit', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_pru_lec_crit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimPruMat',
            fields=[
                ('id_pru_mat', models.AutoField(primary_key=True, serialize=False)),
                ('desemp_mat', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_pru_mat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimPruSocCiu',
            fields=[
                ('id_pru_soc_ciu', models.AutoField(primary_key=True, serialize=False)),
                ('desemp_soc_ciu', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_pru_soc_ciu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimTiempo',
            fields=[
                ('id_tiempo', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.TextField(blank=True, null=True)),
                ('ano', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_tiempo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactSaber11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punt_global', models.IntegerField(blank=True, null=True)),
                ('prom_rend', models.IntegerField(blank=True, null=True)),
                ('punt_c_nat', models.IntegerField(blank=True, null=True)),
                ('punt_ingles', models.IntegerField(blank=True, null=True)),
                ('punt_lec_crit', models.IntegerField(blank=True, null=True)),
                ('punt_mat', models.IntegerField(blank=True, null=True)),
                ('punt_soc_ciu', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_saber11',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DashboardSaber2012',
        ),
        migrations.DeleteModel(
            name='DashboardSaberpro2012',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Saberpro2012',
        ),
        migrations.DeleteModel(
            name='Saberpro2013',
        ),
        migrations.DeleteModel(
            name='Saberpro2014',
        ),
    ]
